default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Rails_React_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: Rails_React_test
  username: postgres
  password: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
